#version: '3.8'

services:
  backend:
    build: ./backend
    container_name: puppygames-backend
    ports:
      - "3001:3001"
    volumes:
      - ./backend/data:/app/data
    environment:
      - PORT=3001
      - JWT_SECRET=super-geheimes-passwort-bitte-aendern
      - DATABASE_PATH=/app/data/puppygames.db
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: puppygames-frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
    restart: unless-stopped